import { useState } from 'react';
import type { OverlayTemplateSummary } from '@vynode/contracts';

const typeLabels = { text: 'Text', tile: 'Tile', variable: 'Variable', raster: 'Image', svg: 'Uploaded icon', icon: 'Library icon', shape: 'Shape', 'mapped-icon': 'Mapped Icon' };

export const CopyOverlayElementsModal = ({ source, templates, onClose, onCopy }: { source: OverlayTemplateSummary; templates: readonly OverlayTemplateSummary[]; onClose(): void; onCopy(elementIds: readonly string[], templateIds: readonly string[]): Promise<void> }) => {
  const [elements,setElements]=useState<string[]>([]);
  const [targets,setTargets]=useState<string[]>([]);
  const [copying,setCopying]=useState(false);
  const available=templates.filter((template)=>template.id!==source.id);
  const toggle=(items:string[],id:string,set:(value:string[])=>void)=>set(items.includes(id)?items.filter((item)=>item!==id):[...items,id]);
  const copy=async()=>{setCopying(true);try{await onCopy(elements,targets);onClose();}finally{setCopying(false)}};
  return <div className="modal-backdrop"><section className="poster-modal copy-elements-modal" role="dialog" aria-modal="true" aria-labelledby="copy-elements-title"><div className="modal-heading"><div><p className="eyebrow">Copying from: {source.name}</p><h2 id="copy-elements-title">Copy elements</h2><p>Select which elements to copy from this template and which templates should receive them.</p></div><button className="icon-button" aria-label="Close copy elements dialog" onClick={onClose}>×</button></div><div className="copy-elements-layout"><section><div className="selection-heading"><strong>Select elements to copy</strong><span><button onClick={()=>setElements(source.design.elements.map((item)=>item.id))}>Select all</button><button onClick={()=>setElements([])}>Deselect all</button></span></div><div className="selection-list">{source.design.elements.length===0?<p>No elements in template</p>:source.design.elements.map((element)=><label className={elements.includes(element.id)?'selected':''} key={element.id}><input type="checkbox" checked={elements.includes(element.id)} onChange={()=>toggle(elements,element.id,setElements)}/><span><strong>{typeLabels[element.type]}</strong><small>{element.type==='text'?String(element.properties.text??'').slice(0,30):`${element.width}×${element.height} at (${element.x}, ${element.y})`}</small></span></label>)}</div></section><section><div className="selection-heading"><strong>Select templates to copy to</strong><span><button onClick={()=>setTargets(available.map((item)=>item.id))}>Select all</button><button onClick={()=>setTargets([])}>Deselect all</button></span></div><div className="selection-list">{available.length===0?<p>No templates available</p>:available.map((template)=><label className={targets.includes(template.id)?'selected':''} key={template.id}><input type="checkbox" checked={targets.includes(template.id)} onChange={()=>toggle(targets,template.id,setTargets)}/><span><strong>{template.name}</strong><small>{template.description}</small></span></label>)}</div></section></div><p className="field-help">Copied elements are appended above existing layers with new unique IDs. If a target contains a matching variable layer from an earlier copy, its configured segments are preserved.</p><footer className="modal-actions"><button className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={!elements.length||!targets.length||copying} onClick={()=>void copy()}>{copying?'Copying…':`Copy ${elements.length} ${elements.length===1?'element':'elements'} to ${targets.length} ${targets.length===1?'template':'templates'}`}</button></footer></section></div>;
};
