import assert from 'node:assert/strict';
import test from 'node:test';
import type { ManagedCollection } from '@vynode/contracts';
import { ProductionCollectionPreview } from './production-collection-preview.js';

const collection:ManagedCollection={id:'collection-1',title:'Popular',description:'',mediaType:'movie',libraryId:'1',libraryName:'Movies',sourceType:'tmdb',sourceSettings:{subtype:'popular',maxItems:10,itemOrder:'default'},itemCount:0,homeVisible:true,recommendedVisible:true,libraryVisible:true,sharedOrder:0,libraryOrder:0,status:'needs-sync',tmdbDiscoverSettings:{movieSortBy:'popularity.desc',tvSortBy:'popularity.desc',filterGroups:[]}};

test('production TMDB preview acquires, matches, and reports missing Plex items',async()=>{
  const requested:string[]=[];
  const preview=new ProductionCollectionPreview({tmdbApiKey:async()=>'secret',integration:async()=>undefined,arrSource:async()=>[],fetch:async(input)=>{requested.push(String(input));return Response.json({results:[{id:10,title:'Available',release_date:'2025-01-01'},{id:20,title:'Missing',release_date:'2024-01-01'}],total_pages:1});},plexQuery:async(path)=>{assert.match(path,/sections\/1\/all/);return{MediaContainer:{Metadata:[{ratingKey:'100',Guid:[{id:'tmdb://10'}]}]}};}});
  const result=await preview.preview(collection);assert.equal(result.fetchedCount,2);assert.equal(result.matchedCount,1);assert.equal(result.missingCount,1);assert.equal(result.items[0]?.plexRatingKey,'100');assert.equal(result.items[1]?.available,false);assert.match(requested[0]??'',/api_key=secret/);
});

test('production preview rejects missing credentials and unsupported providers truthfully',async()=>{
  const preview=new ProductionCollectionPreview({tmdbApiKey:async()=>undefined,integration:async()=>undefined,plexQuery:async()=>({})});
  await assert.rejects(()=>preview.preview(collection),/Configure and test TMDB/);
  await assert.rejects(()=>preview.preview({...collection,sourceType:'seerr'}),/not connected/);
});

test('production Seerr request collections match TMDB and TVDB identities',async()=>{const engine=new ProductionCollectionPreview({tmdbApiKey:async()=>undefined,integration:async()=>undefined,seerrSource:async(mediaType,subtype,limit)=>{assert.equal(mediaType,'movie');assert.equal(subtype,'global');assert.equal(limit,10);return[{title:'Requested Movie',year:2026,tmdbId:44}]},plexQuery:async()=>({MediaContainer:{Metadata:[{ratingKey:'440',Guid:[{id:'tmdb://44'}]}]}})});const result=await engine.preview({...collection,sourceType:'seerr',sourceSettings:{subtype:'global',maxItems:10,itemOrder:'default'}});assert.equal(result.fetchedCount,1);assert.equal(result.matchedCount,1);assert.equal(result.items[0]?.plexRatingKey,'440');});

test('production Seerr private-user collections pass the exact immutable requester id',async()=>{let requester:number|undefined;const engine=new ProductionCollectionPreview({tmdbApiKey:async()=>undefined,integration:async()=>undefined,seerrSource:async(_mediaType,subtype,_limit,requesterId)=>{assert.equal(subtype,'user');requester=requesterId;return[{title:'Private Request',tmdbId:45}]},plexQuery:async()=>({MediaContainer:{Metadata:[{ratingKey:'450',Guid:[{id:'tmdb://45'}]}]}})});const result=await engine.preview({...collection,sourceType:'seerr',sourceSettings:{subtype:'user',seerrUserId:27,maxItems:10,itemOrder:'default'}});assert.equal(requester,27);assert.equal(result.items[0]?.plexRatingKey,'450');await assert.rejects(()=>engine.preview({...collection,sourceType:'seerr',sourceSettings:{subtype:'user',maxItems:10,itemOrder:'default'}}),/valid Seerr user/);});

test('production multi-source composes child providers and deduplicates TMDB identities',async()=>{const multi:ManagedCollection={...collection,sourceType:'multi-source',sourceSettings:{subtype:'',maxItems:10,itemOrder:'default'},multiSourceSettings:{combineMode:'interleaved',sources:[{id:'popular',type:'tmdb',subtype:'popular',priority:0},{id:'rated',type:'tmdb',subtype:'top_rated',priority:1}]}};const preview=new ProductionCollectionPreview({tmdbApiKey:async()=>'secret',integration:async()=>undefined,fetch:async(input)=>Response.json(String(input).includes('top_rated')?{results:[{id:10,title:'Duplicate'},{id:30,title:'Rated'}],total_pages:1}:{results:[{id:10,title:'Duplicate'},{id:20,title:'Popular'}],total_pages:1}),plexQuery:async()=>({MediaContainer:{Metadata:[{ratingKey:'100',Guid:[{id:'tmdb://10'}]},{ratingKey:'200',Guid:[{id:'tmdb://20'}]},{ratingKey:'300',Guid:[{id:'tmdb://30'}]}]}})});const result=await preview.preview(multi);assert.equal(result.fetchedCount,3);assert.equal(result.matchedCount,3);assert.deepEqual(result.items.map((item)=>item.tmdbId),[10,20,30]);});

test('production IMDb preview matches Plex IMDb GUIDs without TMDB credentials',async()=>{const imdb:ManagedCollection={...collection,sourceType:'imdb',sourceSettings:{subtype:'top_250',maxItems:10,itemOrder:'default'}};const preview=new ProductionCollectionPreview({tmdbApiKey:async()=>undefined,integration:async()=>undefined,imdbClient:{async source(){return[{imdbId:'tt001',title:'Available',mediaType:'movie',rank:1},{imdbId:'tt002',title:'Missing',mediaType:'movie',rank:2}];}},plexQuery:async()=>({MediaContainer:{Metadata:[{ratingKey:'501',Guid:[{id:'imdb://tt001'}]}]}})});const result=await preview.preview(imdb);assert.equal(result.matchedCount,1);assert.equal(result.missingCount,1);assert.equal(result.items[0]?.plexRatingKey,'501');});

test('production manual and Plex generator previews validate real library members',async()=>{const engine=new ProductionCollectionPreview({tmdbApiKey:async()=>undefined,integration:async()=>undefined,plexQuery:async()=>({MediaContainer:{Metadata:[{ratingKey:'1',title:'Action Movie',year:2024,Genre:[{tag:'Action'}],Media:[{videoResolution:'4k'}]},{ratingKey:'2',title:'Drama Movie',year:1995,Genre:[{tag:'Drama'}],Media:[{videoResolution:'1080'}]}]}})});const manual:ManagedCollection={...collection,sourceType:'manual',sourceSettings:{subtype:'',maxItems:10,itemOrder:'default',manualMembers:[{ratingKey:'1',title:'Action Movie'},{ratingKey:'999',title:'Deleted'}]}};const manualResult=await engine.preview(manual);assert.equal(manualResult.matchedCount,1);assert.equal(manualResult.missingCount,1);const generated:ManagedCollection={...collection,sourceType:'plex',sourceSettings:{subtype:'genres',maxItems:10,itemOrder:'default',plexGenerator:{selectionMode:'include',selectedValues:['Action'],enabledRatingGroups:[],titleTemplate:'{value}',cleanupMissing:true}}};const generatedResult=await engine.preview(generated);assert.deepEqual(generatedResult.items.map((item)=>item.title),['Action Movie']);});

test('production season preview queries Plex seasons and validates exact manual identities',async()=>{const paths:string[]=[];const engine=new ProductionCollectionPreview({tmdbApiKey:async()=>undefined,integration:async()=>undefined,plexQuery:async(path)=>{paths.push(path);return{MediaContainer:{Metadata:[{ratingKey:'301',title:'Season 1',parentRatingKey:'30',index:1}]}};}});const season:ManagedCollection={...collection,mediaType:'show',itemType:'season',libraryId:'2',libraryName:'TV Shows',sourceType:'manual',sourceSettings:{subtype:'',maxItems:10,itemOrder:'default',manualMembers:[{ratingKey:'301',title:'Season 1',type:'season',parentRatingKey:'30',seasonNumber:1},{ratingKey:'999',title:'Missing',type:'season'}]}};const result=await engine.preview(season);assert.match(paths[0]??'',/[?&]type=3(?:&|$)/);assert.equal(result.matchedCount,1);assert.equal(result.missingCount,1);assert.equal(result.items[0]?.plexRatingKey,'301');});

test('production episode preview queries Plex episodes and validates exact manual identities',async()=>{const paths:string[]=[];const engine=new ProductionCollectionPreview({tmdbApiKey:async()=>undefined,integration:async()=>undefined,plexQuery:async(path)=>{paths.push(path);return{MediaContainer:{Metadata:[{ratingKey:'401',title:'Pilot',parentRatingKey:'301',grandparentRatingKey:'30',parentIndex:1,index:1}]}};}});const episode:ManagedCollection={...collection,mediaType:'show',itemType:'episode',libraryId:'2',libraryName:'TV Shows',sourceType:'manual',sourceSettings:{subtype:'',maxItems:10,itemOrder:'default',manualMembers:[{ratingKey:'401',title:'Pilot',type:'episode',parentRatingKey:'301',grandparentRatingKey:'30',seasonNumber:1,episodeNumber:1},{ratingKey:'999',title:'Missing',type:'episode'}]}};const result=await engine.preview(episode);assert.match(paths[0]??'',/[?&]type=4(?:&|$)/);assert.equal(result.matchedCount,1);assert.equal(result.missingCount,1);assert.equal(result.items[0]?.plexRatingKey,'401');});

test('production Tautulli preview validates returned rating keys against the selected library',async()=>{const tautulli:ManagedCollection={...collection,sourceType:'tautulli',sourceSettings:{subtype:'most_popular_plays',maxItems:10,itemOrder:'default',customDays:30,minimumPlays:2}};const engine=new ProductionCollectionPreview({tmdbApiKey:async()=>undefined,integration:async()=>undefined,tautulliClient:{async source(){return[{ratingKey:'1',title:'Watched',mediaType:'movie',totalPlays:5,totalDurationSeconds:100,uniqueViewers:2,rank:1},{ratingKey:'99',title:'Wrong library',mediaType:'movie',totalPlays:4,totalDurationSeconds:80,uniqueViewers:1,rank:2}];}},plexQuery:async()=>({MediaContainer:{Metadata:[{ratingKey:'1',title:'Watched'}]}})});const result=await engine.preview(tautulli);assert.equal(result.matchedCount,1);assert.equal(result.missingCount,1);assert.equal(result.items[0]?.plexRatingKey,'1');});

test('production Arr tag previews match Radarr TMDB and Sonarr TVDB identities',async()=>{const engine=new ProductionCollectionPreview({tmdbApiKey:async()=>undefined,integration:async()=>undefined,arrSource:async(kind)=>kind==='radarr'?[{title:'Movie',tmdbId:10}]:[{title:'Show',tvdbId:20}],plexQuery:async()=>({MediaContainer:{Metadata:[{ratingKey:'100',Guid:[{id:'tmdb://10'}]},{ratingKey:'200',Guid:[{id:'tvdb://20'}]}]}})});const settings={subtype:'tag',maxItems:10,itemOrder:'default' as const,arrServerId:'server',arrTagId:3};const movie=await engine.preview({...collection,sourceType:'radarrtag',sourceSettings:settings});assert.equal(movie.items[0]?.plexRatingKey,'100');const show=await engine.preview({...collection,mediaType:'show',sourceType:'sonarrtag',sourceSettings:settings});assert.equal(show.items[0]?.plexRatingKey,'200');});

test('production Networks Top 10 resolves FlixPatrol titles through TMDB',async()=>{const requested:string[]=[];const engine=new ProductionCollectionPreview({tmdbApiKey:async()=>'tmdb-key',integration:async()=>undefined,flixpatrolClient:{async source(input){assert.equal(input.platform,'netflix_top_10');assert.equal(input.country,'US');return[{title:'Chart Movie',rank:1,mediaType:'movie'}];}},fetch:async(input)=>{requested.push(String(input));return Response.json({results:[{id:77,title:'Chart Movie',release_date:'2026-01-02'}]});},plexQuery:async()=>({MediaContainer:{Metadata:[{ratingKey:'777',Guid:[{id:'tmdb://77'}]}]}})});const result=await engine.preview({...collection,sourceType:'networks',sourceSettings:{subtype:'netflix_top_10',networkCountry:'US',maxItems:10,itemOrder:'default'}});assert.equal(result.matchedCount,1);assert.equal(result.items[0]?.plexRatingKey,'777');assert.match(requested[0]??'',/search\/movie/);});

test('production Network Originals requires a supported provider and MDBList credentials',async()=>{const engine=new ProductionCollectionPreview({tmdbApiKey:async()=>undefined,integration:async()=>undefined,plexQuery:async()=>({})});await assert.rejects(()=>engine.preview({...collection,sourceType:'originals',sourceSettings:{subtype:'netflix_originals',maxItems:10,itemOrder:'default'}}),/Configure and test MDBList/);});

test('production filtered hubs use real Plex dates and request episodes when selected',async()=>{const paths:string[]=[];const now=Math.floor(Date.now()/1000);const engine=new ProductionCollectionPreview({tmdbApiKey:async()=>undefined,integration:async()=>undefined,plexQuery:async(path)=>{paths.push(path);return{MediaContainer:{Metadata:[{ratingKey:'1',title:'Fresh',addedAt:now-60},{ratingKey:'2',title:'Old',addedAt:now-40*86400}]}};}});const result=await engine.preview({...collection,mediaType:'show',sourceType:'filtered-hub',sourceSettings:{subtype:'recently_added',customDays:30,maxItems:10,itemOrder:'default'}});assert.deepEqual(result.items.map((item)=>item.title),['Fresh']);await engine.preview({...collection,mediaType:'show',sourceType:'filtered-hub',sourceSettings:{subtype:'recently_released_episodes',customDays:30,maxItems:10,itemOrder:'default'}});assert.match(paths[1]??'',/&type=4/);});

test('production TMDB and monitored Arr Coming Soon use their exact acquisition paths',async()=>{const urls:string[]=[];const engine=new ProductionCollectionPreview({tmdbApiKey:async()=>'key',integration:async()=>undefined,arrMonitored:async(kind)=>{assert.equal(kind,'radarr');return[{title:'Monitored Future',tmdbId:99,releaseAt:'2027-01-01'}];},fetch:async(input)=>{urls.push(String(input));return Response.json({results:[{id:88,title:'Future Movie',release_date:'2027-01-01'}],total_pages:1});},plexQuery:async()=>({MediaContainer:{Metadata:[{ratingKey:'999',Guid:[{id:'tmdb://99'}]}]}})});const upcoming=await engine.preview({...collection,sourceType:'comingsoon',sourceSettings:{subtype:'tmdb_anticipated',region:'US',maxItems:10,itemOrder:'default'}});assert.equal(upcoming.items[0]?.tmdbId,88);assert.match(urls[0]??'',/movie\/upcoming/);const monitored=await engine.preview({...collection,sourceType:'comingsoon',sourceSettings:{subtype:'monitored',maxItems:10,itemOrder:'default'}});assert.equal(monitored.items[0]?.plexRatingKey,'999');});
