import assert from 'node:assert/strict';
import { mkdtemp,rm } from 'node:fs/promises'; import { tmpdir } from 'node:os'; import { join } from 'node:path'; import test from 'node:test';
import { OnboardingService } from '@vynode/onboarding'; import { VynodeSqliteStorage } from '@vynode/storage';
import { SqliteArrRepository,SqliteOnboardingRepository,SqlitePlexServerRepository } from './production-repositories.js';

test('persists onboarding with optimistic concurrency',async()=>{ const dir=await mkdtemp(join(tmpdir(),'vynode-repo-')); try { const storage=new VynodeSqliteStorage(join(dir,'vynode.db')); const repo=new SqliteOnboardingRepository(storage,'installation-1'); const service=new OnboardingService(repo); assert.equal((await service.get()).installationId,'installation-1'); const next=await service.apply(0,{type:'complete',stage:'deployment'}); assert.equal(next.revision,1); assert.equal(await repo.compareAndSet(0,next),false); storage.close(); } finally { await rm(dir,{recursive:true,force:true}); } });

test('persists Plex configuration with compare-and-set',async()=>{ const dir=await mkdtemp(join(tmpdir(),'vynode-repo-')); try { const storage=new VynodeSqliteStorage(join(dir,'vynode.db')); const repo=new SqlitePlexServerRepository(storage); const configuration={revision:1,host:'plex.local',port:32400,transport:'http' as const,autoEmptyTrash:false,machineIdentifier:'machine-1',name:'Plex',libraries:[],verifiedAt:'2026-01-01T00:00:00.000Z'}; assert.equal(await repo.compareAndSet(0,configuration),true); assert.equal((await repo.get())?.machineIdentifier,'machine-1'); assert.equal(repo.peek()?.machineIdentifier,'machine-1'); assert.equal(await repo.compareAndSet(0,{...configuration,revision:2}),false); storage.close(); } finally { await rm(dir,{recursive:true,force:true}); } });

test('persists Arr servers and atomically clears conflicting defaults',async()=>{const dir=await mkdtemp(join(tmpdir(),'vynode-arr-repo-'));try{const storage=new VynodeSqliteStorage(join(dir,'vynode.db'));const repo=new SqliteArrRepository(storage);const endpoint={kind:'radarr' as const,name:'Radarr',hostname:'radarr.local',port:7878,useSsl:false,urlBase:''};const selection={kind:'radarr' as const,profileId:1,rootFolder:'/movies',tagIds:[],isDefault:true,is4k:false,automaticTagMode:'off' as const,monitorByDefault:true,searchOnAdd:false,tagExistingItems:false,minimumAvailability:'released' as const};const first={id:'one',revision:1,endpoint,secretReference:'secret-one',selection,verifiedAt:'2026-01-01T00:00:00.000Z'};const second={...first,id:'two',endpoint:{...endpoint,name:'Other'},secretReference:'secret-two'};assert.equal(await repo.compareAndSet('one',0,first,[]),true);assert.equal(await repo.compareAndSet('two',0,second,['one']),true);storage.close();const reopenedStorage=new VynodeSqliteStorage(join(dir,'vynode.db'));const reopened=new SqliteArrRepository(reopenedStorage);assert.equal((await reopened.get('one'))?.selection.isDefault,false);assert.equal((await reopened.get('two'))?.selection.isDefault,true);reopenedStorage.close();}finally{await rm(dir,{recursive:true,force:true});}});
