export interface LetterboxdSourceItem { title:string; year?:number; letterboxdUrl:string }
export interface LetterboxdSourceRequest { subtype:'custom'|'watchlist'|'random'; url?:string; randomUrls?:readonly string[]; limit:number }
export interface LetterboxdClientOptions { fetch?:typeof globalThis.fetch; browserFetch?:(url:string,signal?:AbortSignal)=>Promise<string>; maxPages?:number; random?:()=>number }
const decode=(value:string)=>value.replace(/&lrm;|&rlm;/g,'').replace(/&quot;/g,'"').replace(/&#0?39;|&#x27;/gi,"'").replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&ndash;/g,'–').replace(/&mdash;/g,'—').replace(/&hellip;/g,'…');
export const parseLetterboxdList=(html:string):LetterboxdSourceItem[]=>{const items:LetterboxdSourceItem[]=[];const seen=new Set<string>();for(const match of html.matchAll(/<li[^>]*class="[^"]*(?:posteritem|griditem)[^"]*"[^>]*>(.*?)<\/li>/gs)){const body=match[1]!;const path=/data-(?:target-link|item-link)="([^"]+)"/.exec(body)?.[1];const raw=/data-item-name="([^"]+)"/.exec(body)?.[1];if(!path||!raw||seen.has(path))continue;seen.add(path);const display=/data-item-full-display-name="([^"]+)"/.exec(body)?.[1]??raw;const year=/\((\d{4})\)\s*$/.exec(display)?.[1];items.push({title:decode(raw).replace(/\s*\(\d{4}\)$/,''),letterboxdUrl:new URL(path,'https://letterboxd.com').toString(),...(year?{year:Number(year)}:{})});}return items;};
const normalizedUrl=(value:string)=>{let url:URL;try{url=new URL(value);}catch{throw new Error('Enter a valid Letterboxd list or watchlist URL.');}if(url.protocol!=='https:'||url.hostname!=='letterboxd.com'||url.username||url.password||!/^\/[^/]+\/(?:list\/[^/]+|watchlist)\/?$/.test(url.pathname))throw new Error('Enter a valid Letterboxd list or watchlist URL.');url.search='';url.hash='';return url.toString().replace(/\/$/,'');};
export class LetterboxdClient {readonly #fetch:typeof globalThis.fetch;readonly #browserFetch?:LetterboxdClientOptions['browserFetch'];readonly #maxPages:number;readonly #random:()=>number;public constructor(options:LetterboxdClientOptions={}){this.#fetch=options.fetch??globalThis.fetch;this.#browserFetch=options.browserFetch;this.#maxPages=Math.max(1,Math.min(25,options.maxPages??15));this.#random=options.random??Math.random;}
  public async source(request:LetterboxdSourceRequest,signal?:AbortSignal){const limit=Math.max(1,Math.min(5000,Math.trunc(request.limit)));let selected=request.url;if(request.subtype==='random'){const urls=request.randomUrls?.map(normalizedUrl)??[];if(!urls.length)throw new Error('Add at least one Letterboxd list to the random pool.');selected=urls[Math.min(urls.length-1,Math.floor(this.#random()*urls.length))];}if(!selected)throw new Error('A Letterboxd URL is required.');const base=normalizedUrl(selected);const results:LetterboxdSourceItem[]=[];const seen=new Set<string>();for(let page=1;page<=this.#maxPages&&results.length<limit;page++){const url=`${base}/${page===1?'':`page/${page}/`}`;const html=await this.#page(url,signal);const parsed=parseLetterboxdList(html);if(!parsed.length)break;for(const item of parsed){if(seen.has(item.letterboxdUrl))continue;seen.add(item.letterboxdUrl);results.push(item);if(results.length>=limit)break;}}return results;}
  async #page(url:string,signal?:AbortSignal){let response:Response;try{response=await this.#fetch(url,{headers:{Accept:'text/html','User-Agent':'Vynode/0.1'},...(signal?{signal}:{})});}catch(error){if(error instanceof Error&&error.name==='AbortError')throw error;if(this.#browserFetch)return this.#browserFetch(url,signal);throw new Error('Letterboxd is unavailable.',{cause:error});}const html=await response.text();if(response.ok&&!/cf-chl-|Just a moment/i.test(html))return html;if(this.#browserFetch&&(response.status===403||response.status===429||/cf-chl-|Just a moment/i.test(html)))return this.#browserFetch(url,signal);throw new Error(`Letterboxd request failed (status ${response.status}).`);}
}
