export type TmdbMediaType='movie'|'show';
export interface TmdbSourceItem { tmdbId:number; mediaType:TmdbMediaType; title:string; year?:number; overview?:string; posterPath?:string; popularity?:number; voteAverage?:number }
export interface TmdbSourceRequest { mediaType:TmdbMediaType; subtype:'trending_day'|'trending_week'|'popular'|'top_rated'|'upcoming'|'custom'|'discover'; limit:number; customUrl?:string; discover?:Readonly<Record<string,string|number|boolean>>; language?:string; region?:string }
export interface TmdbClientOptions { apiKey:string; fetch?:typeof globalThis.fetch; baseUrl?:string; maxPages?:number }
type TmdbRow={id?:number;title?:string;name?:string;release_date?:string;first_air_date?:string;overview?:string;poster_path?:string;popularity?:number;vote_average?:number;media_type?:string};
const positive=(value:unknown)=>typeof value==='number'&&Number.isSafeInteger(value)&&value>0?value:undefined;

export class TmdbSourceClient {
  readonly #fetch:typeof globalThis.fetch; readonly #apiKey:string; readonly #baseUrl:string; readonly #maxPages:number;
  public constructor(options:TmdbClientOptions){ this.#apiKey=options.apiKey.trim(); if(!this.#apiKey) throw new Error('A TMDB API key is required.'); this.#fetch=options.fetch??globalThis.fetch; this.#baseUrl=options.baseUrl??'https://api.themoviedb.org/3'; this.#maxPages=Math.max(1,Math.min(100,options.maxPages??20)); }
  public async source(request:TmdbSourceRequest,signal?:AbortSignal):Promise<readonly TmdbSourceItem[]>{
    const limit=Math.max(1,Math.min(5000,Math.trunc(request.limit))); const endpoint=this.#endpoint(request); const results:TmdbSourceItem[]=[]; const seen=new Set<number>();
    for(let page=1;page<=this.#maxPages&&results.length<limit;page++){
      const url=new URL(`${this.#baseUrl}${endpoint.path}`); url.searchParams.set('api_key',this.#apiKey); url.searchParams.set('page',String(page)); url.searchParams.set('language',request.language?.trim()||'en-US'); if(request.region) url.searchParams.set('region',request.region); for(const [key,value] of Object.entries(endpoint.parameters)) if(value!==''&&value!==false) url.searchParams.set(key,String(value));
      let response:Response; try{response=await this.#fetch(url,{headers:{Accept:'application/json'},...(signal?{signal}:{})});}catch(error){if(error instanceof Error&&error.name==='AbortError')throw error;throw new Error('TMDB is unavailable.',{cause:error});}
      if(!response.ok) throw new Error(response.status===401||response.status===403?'TMDB rejected the configured API key.':response.status===429?'TMDB rate limited the request.':`TMDB request failed (status ${response.status}).`);
      const payload=await response.json() as {results?:TmdbRow[];items?:TmdbRow[];parts?:TmdbRow[];total_pages?:number}; const rows=payload.results??payload.items??payload.parts??[];
      for(const row of rows){const id=positive(row.id);const title=(row.title??row.name)?.trim();if(!id||!title||seen.has(id))continue;seen.add(id);const date=row.release_date??row.first_air_date;const year=date&&/^\d{4}/.test(date)?Number(date.slice(0,4)):undefined;results.push({tmdbId:id,mediaType:row.media_type==='tv'?'show':row.media_type==='movie'?'movie':request.mediaType,title,...(year?{year}:{}),...(row.overview?{overview:row.overview}:{}),...(row.poster_path?{posterPath:row.poster_path}:{}),...(typeof row.popularity==='number'?{popularity:row.popularity}:{}),...(typeof row.vote_average==='number'?{voteAverage:row.vote_average}:{})});if(results.length>=limit)break;}
      if(!rows.length||page>=Math.min(this.#maxPages,positive(payload.total_pages)??1)||['/collection/','/list/'].some((prefix)=>endpoint.path.startsWith(prefix)))break;
    }
    return results;
  }
  public async search(mediaType:TmdbMediaType,title:string,year?:number,signal?:AbortSignal):Promise<TmdbSourceItem|undefined>{const query=title.trim();if(!query)return undefined;const url=new URL(`${this.#baseUrl}/search/${mediaType==='show'?'tv':'movie'}`);url.searchParams.set('api_key',this.#apiKey);url.searchParams.set('query',query);if(year)url.searchParams.set(mediaType==='show'?'first_air_date_year':'year',String(year));let response:Response;try{response=await this.#fetch(url,{headers:{Accept:'application/json'},...(signal?{signal}:{})});}catch(error){if(error instanceof Error&&error.name==='AbortError')throw error;throw new Error('TMDB is unavailable.',{cause:error});}if(!response.ok)throw new Error(response.status===401||response.status===403?'TMDB rejected the configured API key.':`TMDB search failed (status ${response.status}).`);const rows=((await response.json())as{results?:TmdbRow[]}).results??[];const normalized=query.toLocaleLowerCase();const row=rows.find((item)=>(item.title??item.name)?.trim().toLocaleLowerCase()===normalized)??rows[0];const id=positive(row?.id),name=(row?.title??row?.name)?.trim();if(!row||!id||!name)return undefined;const date=row.release_date??row.first_air_date;const foundYear=date&&/^\d{4}/.test(date)?Number(date.slice(0,4)):undefined;return{tmdbId:id,mediaType,title:name,...(foundYear?{year:foundYear}:{}),...(row.overview?{overview:row.overview}:{}),...(row.poster_path?{posterPath:row.poster_path}:{})};}
  #endpoint(request:TmdbSourceRequest):{path:string;parameters:Readonly<Record<string,string|number|boolean>>}{const media=request.mediaType==='show'?'tv':'movie';if(request.subtype==='trending_day'||request.subtype==='trending_week')return{path:`/trending/${media}/${request.subtype.endsWith('day')?'day':'week'}`,parameters:{}};if(request.subtype==='popular'||request.subtype==='top_rated')return{path:`/${media}/${request.subtype}`,parameters:{}};if(request.subtype==='upcoming')return{path:request.mediaType==='movie'?'/movie/upcoming':'/discover/tv',parameters:request.mediaType==='show'?{'first_air_date.gte':new Date().toISOString().slice(0,10),sort_by:'popularity.desc'}:{}};if(request.subtype==='discover')return{path:`/discover/${media}`,parameters:request.discover??{}};if(request.subtype==='custom'){const match=request.customUrl?.match(/themoviedb\.org\/(collection|list|network|company)\/(\d+)(?:[^/]*\/)?(movie|tv)?/i);if(!match)throw new Error('Enter a valid TMDB collection, list, network, or company URL.');const [,kind,id,type]=match;if(kind==='collection')return{path:`/collection/${id}`,parameters:{}};if(kind==='list')return{path:`/list/${id}`,parameters:{}};return{path:`/discover/${type==='tv'?'tv':type==='movie'?'movie':media}`,parameters:{[kind==='network'?'with_networks':'with_companies']:id!}};}throw new Error(`Unsupported TMDB source subtype: ${request.subtype}`);}
}
